@startuml
title De was doen

start
:User selects
washing program
from list;

:User selects temperature;

:Start button
pressed;
partition "De was doen" {
:Execute washing program;
stop

:Stop button pressed;
}

:Stops whatever the washing machine is doing;
if (Is there water in the machine?) then (Yes)
	:Pump out the water;
	:unlock the door;
else (No)
endif
stop
@enduml

@startuml
title WashingProgram
start
repeat
    :Reads an instruction from the program;
    if(Set water level) then(yes)
        :Set the water level;
    else if(Set temperature) then (yes)
        :Set the temperature;
    else if(Shake) then (yes)
        :Shake the clothes;
    else if(Centrifuge) then (yes)
        :Centrifuge the clothes;
    else if (Slow) then (yes)
        :Slowly rotate the clothes;
    else if (Wait for water) then (yes)
        :wait for the water level to be on the right level;
    else if (Wait for temperature) then (yes)
        :wait for the temperature to be right;




'Wasprogramma'
@enduml

@startuml
title Settings
start
'settings here'
@enduml

@startuml
title Update
start
if (New update detected) then
	:Pop-up comes up
	showing the user
	that a new update
	is available;
	if (Accept the update?) then
		:Update the
		washingmachine;
	else (No)
	endif
else (Else)
endif
stop
@enduml

@startuml
title Authorization
start
    repeat
	:waiting for the input of a pincode;
	if () then(Pincode is entered)
		if (code is correct) then (Yes)
    	    stop
    	else(No)
    	endif
    else(Selected to input restore code)
    :restore code entered;
    if (is restore code correct) then (Yes)
        stop
    else(No)

@enduml