.PHONY: clean All

All:
	@echo "----------Building project:[ ServerSocketHandler - Debug ]----------"
	@cd "ServerSocketHandler" && "$(MAKE)" -f  "ServerSocketHandler.mk"
clean:
	@echo "----------Cleaning project:[ ServerSocketHandler - Debug ]----------"
	@cd "ServerSocketHandler" && "$(MAKE)" -f  "ServerSocketHandler.mk" clean
